theme: jekyll-theme-cayman
title: "Deborah Akinyeye Portfolio"
<head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Deborah Akinyeye Portfolio</title>
<meta name="generator" content="Jekyll v3.9.2">
<meta property="og:title" content="Deborah Akinyeye">
<meta property="og:locale" content="en_US">
<meta name="description" content="My Projects">
<meta property="og:description" content="My Projects">
<link rel="canonical" href="https://deborahakinyeye.github.io/">
<meta property="og:url" content="https://deborahakinyeye.github.io/">
<meta property="og:site_name" content="Deborah Akinyeye Portfolio">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary">
<meta property="twitter:title" content="Data-storytelling-project">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","description":"My Projects","headline":"Deborah Akinyeye Portfolio","name":"Deborah Akinyeye Portfolio","url":"https://deborahakinyeye.github.io/"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;display=swap" as="style" type="text/css" crossorigin="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="stylesheet" href="/assets/css/style.css?v=0b3e6452c8716cce38b6ea655822db2745b20d51">
    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" -->

<!-- end custom head snippets -->

  </head>
